from setuptools import find_packages, setup

setup(
    name="generator",
    version="0.1.0",
    description="Reproduction of GENERator (arXiv:2502.07272), generated by ArXivist",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.10",
    install_requires=[
        "torch>=2.1",
        "transformers>=4.44",
        "accelerate>=0.30",
        "datasets>=2.14",
        "genomic-benchmarks>=0.0.9",
        "huggingface_hub>=0.19",
        "scikit-learn>=1.3",
        "pandas>=2.0",
        "pyyaml>=6.0",
        "tqdm>=4.66",
        "numpy>=1.24",
    ],
)
