"""
arxivist_artemis
==================

Reproduction repository for:
    Rahul D Ray (2026). "ARTEMIS: A Neuro-Symbolic Framework for
    Economically Constrained Market Dynamics." arXiv:2603.18107.

ARTEMIS combines:
    Module 1: Laplace Neural Operator (continuous-time encoder, Section 4.1)
    Module 2: Neural SDE latent dynamics (Section 4.2)
    Physics losses: Feynman-Kac PDE residual + market-price-of-risk penalty (Section 4.2.1-4.2.2)
    Module 3: Differentiable symbolic bottleneck (Section 4.3)
    Module 4: Adaptive conformal allocation + optional Kelly portfolio QP (Section 4.4)

IMPORTANT: several core hyperparameters (latent dimension, SDE step count, loss
weights, symbolic basis library) are never given numeric values in the source
paper. See README.md and configs/config.yaml for the full, explicitly-flagged
list of ASSUMED defaults. See sir-registry/arxiv_2603_18107/sir.json for the
complete provenance and confidence annotations behind every assumption.

Generated by the ArXivist Code Generator (Stage 4) from architecture_plan.json.
"""

__version__ = "0.1.0"

from arxivist_artemis.models.artemis import ARTEMIS
from arxivist_artemis.models.laplace_neural_operator import LaplaceNeuralOperator
from arxivist_artemis.models.neural_sde import NeuralSDE, DriftNet, DiffusionNet
from arxivist_artemis.models.physics_losses import PhysicsLosses, AuxiliaryPricingNet
from arxivist_artemis.models.symbolic_bottleneck import SymbolicBottleneck, BasisLibrary
from arxivist_artemis.models.conformal_allocation import AdaptiveConformalPredictor, KellyPortfolioLayer

__all__ = [
    "ARTEMIS",
    "LaplaceNeuralOperator",
    "NeuralSDE", "DriftNet", "DiffusionNet",
    "PhysicsLosses", "AuxiliaryPricingNet",
    "SymbolicBottleneck", "BasisLibrary",
    "AdaptiveConformalPredictor", "KellyPortfolioLayer",
]
