"""
nerf — Neural Radiance Fields for View Synthesis.

Reproduction of Mildenhall et al., "NeRF: Representing Scenes as Neural
Radiance Fields for View Synthesis" (arXiv:2003.08934), generated by the
ArXivist pipeline (paper_id=arxiv_2003_08934).
"""

__version__ = "0.1.0"
