"""
setup.py — packaging for the NeRF reproduction repo.

Reproduces: Mildenhall et al., "NeRF: Representing Scenes as Neural Radiance
Fields for View Synthesis" (arXiv:2003.08934). Generated by ArXivist Stage 4
(Code Generator) from architecture_plan.json.
"""

from setuptools import setup, find_packages

setup(
    name="nerf-reproduction",
    version="0.1.0",
    description=(
        "Reproduction of NeRF: Representing Scenes as Neural Radiance "
        "Fields for View Synthesis (Mildenhall et al., arXiv:2003.08934)"
    ),
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    python_requires=">=3.10",
    install_requires=[
        line.strip()
        for line in open("requirements.txt")
        if line.strip() and not line.startswith("#")
    ],
)
