from setuptools import find_packages, setup

setup(
    name="dnagpt",
    version="0.1.0",
    description="Reproduction of DNAGPT (arXiv:2307.05628), generated by ArXivist",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.10",
    install_requires=[
        "torch>=2.1",
        "numpy>=1.24",
        "scikit-learn>=1.3",
        "scipy>=1.10",
        "pandas>=2.0",
        "gdown>=5.0",
        "biopython>=1.81",
        "pyyaml>=6.0",
        "tqdm>=4.66",
    ],
)
